database:
  db: 
  user: 
  pass: 

cache:
  cache_path: /var/restfulcache
  expiration: 300

flask:
  secret_key: "your_secure_key_here"
  secure_cookie: True

crypto:
  cookie_key: "your_cookie_key_here"

pfsense:
    server: 
    client-id: 
    client-key: 

email:
    server: 
    address: 
    username: 
    password: 

backblaze:
    bucket-name:
    key-id: 
    auth-key: 

share:
    upload-endpoint:
    public-path: 
    upload-tmp-path: './upload_tmp'

discord:
    token-url: 
    client-id: 
    client-secret: 
    callback-url: 
    data-url: 
    
tachi:
    token-url: 
    user-url: 
    client-id: 
    client-secret: 
    callback-url: 

bad-maniac:
    endpoint: 
    auth-key: 

record_cache_dir: '/tmp'